version: '3.5'

services:
  devshell:
    image: hub.foundries.io/lmp/qimsdk:v94
    build: ./
    restart: unless-stopped
    network_mode: host
    entrypoint: /usr/local/bin/dev-shell
    stop_grace_period: 1s
    environment:
      - SSHD_ENABLE=1
    volumes:
      - /opt:/opt
